site_name: help.unhcr.org
pages:
- [index.md, Home]
- [file_structure.md, File Structure]
- [javascript.md, Javascripts]
- [css.md, CSS]
- [deploy.md, Deploy]
- [plugins.md, Plugins]
- [docs.md, Docs]
theme: readthedocs
